apiVersion: apps/v1
kind: Deployment
metadata:
  name: grace-receiver
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: grace-receiver
      labels:
        app: grace-receiver
        humio-parser: clearway
    spec:
      containers:
      - image: grace_receiver:latest
        imagePullPolicy: IfNotPresent
        name: grace-receiver
        env:
          - name: WRITE_TO_FILE
            valueFrom:
              configMapKeyRef:
                name: config-parms
                key: WRITE_TO_FILE
          - name: WORKERS_COUNT
            valueFrom:
              configMapKeyRef:
                name: config-parms
                key: WORKERS_COUNT
          - name: RABBITMQ_SERVICE_HOST
            value: $(GRACE_RABBITMQ_SERVICE_HOST)
          - name: RABBITMQ_SERVICE_PORT
            value: $(GRACE_RABBITMQ_SERVICE_PORT)
          - name: RABBITMQ_USERNAME
            value: rabbitmq
          - name: RABBITMQ_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: grace-rabbitmq
                    key: rabbitmq-password
  selector:
    matchLabels:
      app: grace-receiver
